"""add new field

Revision ID: 317148ca5c4b
Revises: 21de7cc2a22e
Create Date: 2026-04-09 02:18:27.910420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317148ca5c4b'
down_revision: Union[str, Sequence[str], None] = '21de7cc2a22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'canceled_at')
    # ### end Alembic commands ###
