"""change_column_name

Revision ID: 3906db666b7f
Revises: a0373a2ac093
Create Date: 2026-04-07 16:07:31.030341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3906db666b7f'
down_revision: Union[str, Sequence[str], None] = 'a0373a2ac093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "icon", new_column_name="icon_path")
# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'icon_path')
    # ### end Alembic commands ###
