"""integer

Revision ID: a0373a2ac093
Revises: 1f4e94d16616
Create Date: 2026-04-07 01:44:31.975914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0373a2ac093'
down_revision: Union[str, Sequence[str], None] = '1f4e94d16616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reviews",
        "rating",
        existing_type=sa.NUMERIC(precision=2, scale=1),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="rating::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rating',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=2, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###
