"""remove text

Revision ID: b489e26c197e
Revises: 0981953ae90a
Create Date: 2026-03-18 09:36:32.587539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b489e26c197e'
down_revision: Union[str, Sequence[str], None] = '0981953ae90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=True)
    # ### end Alembic commands ###
