"""rem fields

Revision ID: c3751e0dc5ac
Revises: fc555924d2c2
Create Date: 2026-03-18 09:00:02.773211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3751e0dc5ac'
down_revision: Union[str, Sequence[str], None] = 'fc555924d2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fabricators', 'address')
    op.drop_column('fabricators', 'total_products')
    op.drop_column('fabricators', 'image_url')
    op.drop_column('fabricators', 'email')
    op.drop_column('fabricators', 'description')
    op.drop_column('fabricators', 'rating')
    op.drop_column('fabricators', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fabricators', sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fabricators', sa.Column('rating', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('fabricators', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fabricators', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fabricators', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fabricators', sa.Column('total_products', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fabricators', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
