"""add

Revision ID: fc555924d2c2
Revises: 3dfb9176e47c
Create Date: 2026-03-18 07:21:48.561914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc555924d2c2'
down_revision: Union[str, Sequence[str], None] = '3dfb9176e47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fabricators', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fabricators', 'image_url')
    # ### end Alembic commands ###
